### ISSUE TITLE
[BUG] Source collection changes happening during the execution of ToObservableChangeSet are not reflected.

### ISSUE THREAD

**Issue by kpto** [reactivemarbles/DynamicData#332]
**Describe the bug**

When converting an observable collection to an observable change set, if there is an item added to the observable collection after the collection has been cloned to an inner list of `ChangeAwareList` (Line 44 in `ChangeAwareList.cs`) and before `source.ObserveCollectionChanges()` (Line 136 in `ObservableCollectionEx.cs`), the item is not added to the inner list. If later I remove the item from the observable collection, DynamicData also tries to removes the same item from the inner list and throw `System.ArgumentOutOfRangeException` because the inner list is empty.

**Steps To Reproduce**

The following code can reproduce the bug quite frequently, the time of delay may need adjustment on different machine.
```
        public void RunTest()
        {
            foreach (var i in Enumerable.Range(0, 100))
            {
                var source = new ObservableCollection<int>();
                var dest = new ObservableCollectionExtended<int>();

                var t = Task.Run(async () =>
                {
                    await Task.Delay(55);
                    source.Add(0);
                });

                source
                    .ToObservableChangeSet()
                    .Bind(dest)
                    .Subscribe();

                t.Wait();

                source.RemoveAt(0);
            }
        }
```

The following exception is thrown:
```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at DynamicData.ChangeAwareList`1.RemoveItem(Int32 index) in /Users/paul/Documents/GitHub/SnagrMobile/src/ExternalModules/DynamicData/src/DynamicData/List/ChangeAwareList.cs:line 420
   at DynamicData.ChangeAwareList`1.RemoveAt(Int32 index) in /Users/paul/Documents/GitHub/SnagrMobile/src/ExternalModules/DynamicData/src/DynamicData/List/ChangeAwareList.cs:line 697
   at DynamicData.Binding.ObservableCollectionEx.<>c__DisplayClass4_0`2.<ToObservableChangeSet>b__1(ChangeAwareList`1 list, EventPattern`1 args) in /Users/paul/Documents/GitHub/SnagrMobile/src/ExternalModules/DynamicData/src/DynamicData/Binding/ObservableCollectionEx.cs:line 161
   at System.Reactive.Linq.ObservableImpl.Scan`2._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Scan.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServicesImpl.cs:line 16
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServices.cs:line 14
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Stubs.cs:line 16
   at System.Reactive.AnonymousObserver`1.OnErrorCore(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 73
   at System.Reactive.ObserverBase`1.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 61
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:line 77
   at System.Reactive.ObserverBase`1.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 61
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 61
   at System.Reactive.Sink`2.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 97
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 61
   at System.Reactive.Concurrency.Synchronize`1._.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Synchronization.Synchronize.cs:line 50
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:line 77
   at System.Reactive.ObserverBase`1.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 61
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 61
   at System.Reactive.Sink`2.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 97
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 61
   at System.Reactive.Linq.ObservableImpl.Scan`2._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Scan.cs:line 44
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\FromEventPattern.cs:line 39
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
   at Library.Class1.RunTest() in /Users/paul/Projects/Playground/Library/Class1.cs:line 35
   at Playground.Program.Main(String[] args) in /Users/paul/Projects/Playground/Playground/Program.cs:line 12
```

**Expected behavior**

No exception is thrown and the `dest` collection is the same as the `source`.

**Environment**

- OS:       macOS 10.15.2
- Device:   Mac
- Version:   master branch (The only change is that I removed `;net461;uap10.0.16299` from `DynamicData.csproj` as I cannot build against `uap`)
- Working Version: N/A

**Additional context**
Probably similar to #319 ? Both of them is about thread safety.

**Comment by RolandPheasant** [comment]
My suspicion is quite simply that I aways made an assumption that because the obs collection source is not a thread safe collection that it is the responsibility of the consumer to sychronize access. However I will run your example and dig a little deeper

**Comment by kpto** [comment]
I totally understand that DynamicData is not responsible to secure thread safety. I was planning to post a question on StackOverflow asking what is the best pattern to avoid this problem but then I found #319 which is also about thread safety and it is reported as a bug, so I reported my finding as a bug. I apologize if I did it wrong.
