### ISSUE TITLE
[Bug]: System.ArgumentException: index cannot be greater than the size of the collection

### ISSUE THREAD

**Issue by jay1891** [reactivemarbles/DynamicData#683]
### Describe the bug 🐞

Regulary when we start our application we get the following exception and the application crashes. Could you maybe tell what is the best way to catch the exception, so I can be more specific about the situation?

`System.ArgumentException: index cannot be greater than the size of the collection
   at DynamicData.ChangeAwareList`1.Insert(Int32 index, T item) in /_/src/DynamicData/List/ChangeAwareList.cs:line 223
   at DynamicData.Binding.ObservableCollectionEx.<>c__DisplayClass5_0`2.<ToObservableChangeSet>b__1(ChangeAwareList`1 list, EventPattern`1 args) in /_/src/DynamicData/Binding/ObservableCollectionEx.cs:line 159
   at System.Reactive.Linq.ObservableImpl.Scan`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Scan.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.ObserverBase`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 61
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/AutoDetachObserver.cs:line 77
   at System.Reactive.ObserverBase`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 61
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 61
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 61
   at System.Reactive.Concurrency.Synchronize`1._.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.Synchronize.cs:line 50
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/AutoDetachObserver.cs:line 77
   at System.Reactive.ObserverBase`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 61
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 61
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 573
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 509
   at System.Reactive.Concurrency.EventLoopScheduler.Run() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs:line 356
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

### Step to reproduce

Currently I can not reproduce it yet. 

### Reproduction repository

None at the moment

### Expected behavior

No exception

### DynamicData Version

7.12.11

**Comment by RolandPheasant** [comment]
Yikes. The clue perhaps is here: ObservableCollectionEx

Somewhere you will be observing an Observable collection, either using `ObserveCollectionChanges()` or `ToObservableChangeSet()`.  Do you have many usages of that on an ObservableCollection or ReadOnlyObservableCollection ?

Looking further the issue is here: 

https://github.com/reactivemarbles/DynamicData/blob/957135af7a0fcf72a57f3abfeaa3ec7aea85db37/src/DynamicData/Binding/ObservableCollectionEx.cs#L159

Also I see from the stack trace and event loop scheduler is being used somewhere. Is that the case? Could it be that the observation of a non-thread safe collection is occurring on a thread which is different to the producer thread?

**Comment by jay1891** [comment]
Hi Roland,

Thank you for your reply. Yes I'm looking into the ObservableCollectionEx class to understand more. Our application has in the core a continous monitoring of vessels with each vessel on a designated EventLoopScheduler. This to have sequential updates of the core state of each vessel. That is what you see. When our application view wants to look to state changes of a vessel, the application view (on the uit thread) subscribes on these state changes (which happen on the event loop scheduler). It is during the subscription of the view on a vessel state at startup that sometimes there is a crash.

**Comment by jay1891** [comment]
Do you mean we can have no observable collection on the event loop scheduler so we should use then e.g. the SourceList?

**Comment by RolandPheasant** [comment]
When I designed the observations of  an observable collection I assumed the only usage would be a bound UI list being observed. In that case thread safety is inherent due to the rule of thread affinity. However usage always outstrips design!

**Comment by RolandPheasant** [comment]
You could use a source list, or alternatively add some locking using .Synchronize(). You'd have to work out exactly where however.

**Comment by jay1891** [comment]
Ok, thank you for this insight Roland! 

Is there a way to catch exceptions that occur at this level, instead the application crashes? I can not find any hooks to catch it.

**Comment by RolandPheasant** [comment]
Normally you would just hook into the exception handle of the subscribe. However it's never that simple due to multiple subscribers being a possibility.  It's been a while since I used Rx in my day job so I cannot remember the other alternatives. There are some however. I'll get back when I remember what they are.

**Comment by jay1891** [comment]
Thank you Roland for the clarifications! I will look more into exception handling of Rx, to pinpoint the exception location.

**Comment by RolandPheasant** [comment]
Actually, I wonder whether there is a simple fix.  A lock could be applied before this line:

https://github.com/reactivemarbles/DynamicData/blob/957135af7a0fcf72a57f3abfeaa3ec7aea85db37/src/DynamicData/Binding/ObservableCollectionEx.cs#L149

```cs
source
  .Synchronize(...)
  .ObserveCollectionChanges()
  .Scan(...)
```

**Comment by jay1891** [comment]
Next week I will implement better logging by hooking into Rx exception handling. I shall try to see if I can can do this. Although in general I think I better refractor out the observable collection(s), because as I read in the past from you that Source List is thread safe, so using source list looks like the safest/proven way to go.
